name: Generate GH Stats

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */5 * * *" 

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Generate Stats IMGs
        uses: suisei-cn/actions-download-file@v1.4.0
        id: gh-stats
        with:
          url: "https://github-readme-stats.vercel.app/api?username=resenkkomj&show_icons=true&theme=dark&bg_color=65,00000000,1f2c3c40,50d7f610&rank_icon=github&icon_color=00B0C0&ring_color=00B0C0&text_color=c2c2c2"
          target: dist/
          filename: gh-stats.svg

      - name: push svgs to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}