name: Snake Game

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # allows to manually run the job at any time
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      
      - name: generate svgs
        uses: Platane/snk@v3
        with:
          github_user_name: henriisylvan
      
          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake-dark.svg?color_snake=#D3D3D3&color_dots=#161B21,#012032,#043445,#0F626D,#00B0C6
            dist/github-snake-light.svg?color_snake=#FF01A6&color_dots=#ECEDF1,#9AE9E3,#40C1C3,#309EA1,#216A6E
        env:
          # a github token is required to fetch the contribution calendar from github API
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}

      - name: push svgs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-game-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
